# from <https://github.com/taocpp/PEGTL/blob/master/.travis.yml>

language: cpp

os: linux
sudo: false

env:
    - CXX_COMPILER=g++-4.9
    - CXX_COMPILER=g++-5
    - CXX_COMPILER=g++-6
    - CXX_COMPILER=g++-7
    - CXX_COMPILER=g++-8
    - CXX_COMPILER=clang++-3.8
    - CXX_COMPILER=clang++-3.9
    - CXX_COMPILER=clang++-4.0
    - CXX_COMPILER=clang++-5.0
    - CXX_COMPILER=clang++-6.0
    - CXX_COMPILER=clang++-7
    - CXX_COMPILER=clang++-8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    update: false

before_install:
  - if [[ "${CXX_COMPILER}" =~ "clang++" ]]; then wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -; sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-$(lsb_release -c | awk '{printf $2}')-${CXX_COMPILER##*-} main" -y; fi
  - sudo apt-get update
  - sudo apt-get install "${CXX_COMPILER}" cmake pkg-config $(if [[ "${CXX_COMPILER}" =~ "clang++-" ]]; then echo llvm; fi) -y

before_script:
  - export CXX="${CXX_COMPILER}"
  - export GTEST_COLOR=1

  # not much better than git submodules, but there was never a need/want for the repo in this repo
  - cd ..
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS="-std=c++11"
  - make
  - cd ../../Encryptions/tests

script:
  - make
  - make test
